<html lang="">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>测试报告</title>
</head>
<h2 align="center">测试时间：2022_08_18 08：56：12</h2>
<h2 align="center">用例数：6</h2>
<h2 align="center">成功数：2&nbsp;&nbsp;&nbsp;&nbsp;成功率：33.33333333333333%</h2>
<h2 align="center">失败数：5&nbsp;&nbsp;&nbsp;&nbsp;失败率：83.33333333333334%</h2>



    <table border="1" width = "40%" cellspacing='0' cellpadding='0' align="center">
    <tr>
        <th>用例名称</th>
        <th>报错信息</th>
        <th>校验关键字</th>
<!--        <th>校验结果</th>-->
        <th>总结果</th>
    </tr>

    
    <tr align='center'>
        <td>验证码登录</td>
        <td>Traceback (most recent call last):
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 105, in execute_case
    func(dr, target, value)
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 42, in do_type
    wait_element(dr, elm_loc).send_keys(value)
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 46, in wait_element
    wait.until(lambda dr: dr.find_element(*elm_loc))
  File "C:\Python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

</td>
        <td>None</td>
<!--        <td></td>-->
        <td>失败</td>
    </tr>
    
    <tr align='center'>
        <td>密码登录3</td>
        <td>无</td>
        <td>None</td>
<!--        <td></td>-->
        <td>成功</td>
    </tr>
    
    <tr align='center'>
        <td>密码登录</td>
        <td>Traceback (most recent call last):
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 105, in execute_case
    func(dr, target, value)
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 42, in do_type
    wait_element(dr, elm_loc).send_keys(value)
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 46, in wait_element
    wait.until(lambda dr: dr.find_element(*elm_loc))
  File "C:\Python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

</td>
        <td>None</td>
<!--        <td></td>-->
        <td>失败</td>
    </tr>
    
    <tr align='center'>
        <td>打开百度首页</td>
        <td>无</td>
        <td>None</td>
<!--        <td></td>-->
        <td>成功</td>
    </tr>
    
    <tr align='center'>
        <td>密码登录3</td>
        <td>Traceback (most recent call last):
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 105, in execute_case
    func(dr, target, value)
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 42, in do_type
    wait_element(dr, elm_loc).send_keys(value)
  File "C:\pythonPro\web_ui\test_case\baidu\web_test.py", line 46, in wait_element
    wait.until(lambda dr: dr.find_element(*elm_loc))
  File "C:\Python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

</td>
        <td>None</td>
<!--        <td></td>-->
        <td>失败</td>
    </tr>
    
    <tr align='center'>
        <td>百度搜索2</td>
        <td>无</td>
        <td>90903909</td>
<!--        <td></td>-->
        <td>失败</td>
    </tr>
    
    <tr align='center'>
        <td>百度搜索</td>
        <td>无</td>
        <td>123123123123</td>
<!--        <td></td>-->
        <td>失败</td>
    </tr>
    

    </table>
    </body>
</html>